export const counsellors = [
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "Branch Counsellor, IEEE DITU",
  },
];

export const studentCouncil = [
  {
    porfileUrl: "/avatars/himanshu.svg",
    name: "Himanshu Rawat",
    description: "Chairperson, IEEE DITU",
    github: "https://github.com/0xCipher-max",
    linkedin: "https://www.linkedin.com/in/himanshu-rawat0509/",
  },
  {
    porfileUrl: "/avatars/mukul.svg",
    name: "Mukul Goel",
    description: "Vice Chairperson, IEEE DITU",
    github: "",
    linkedin: "https://www.linkedin.com/in/mukul-goel-157a991b7/",
  },
  {
    porfileUrl: "/avatars/amisha.svg",
    name: "Amisha Tandon",
    description: "Secretary, IEEE DITU",
    github: "",
    linkedin: "https://www.linkedin.com/in/amisha-tandon-750b22226/",
  },
  {
    porfileUrl: "/avatars/prasuk.svg",
    name: "Prasuk Jain",
    description: "Chairperson, CS DITU",
    github: "",
    linkedin: "https://www.linkedin.com/in/prasuk-jain-675058208/",
  },
  {
    porfileUrl: "/avatars/nipurn.svg",
    name: "Nipurn Mehta",
    description: "Treasurer, IEEE DITU",
    github: "",
    linkedin: "https://www.linkedin.com/in/nipurn-mehta/",
  },
  {
    porfileUrl: "/avatars/vijayant.svg",
    name: "Vijayant Singh",
    description: "Technical Head, IEEE DITU",
    github: "https://github.com/TheDarkLord100",
    linkedin: "https://www.linkedin.com/in/vijayant-singh/",
  },
  {
    porfileUrl: "/avatars/sahil.svg",
    name: "Sahil Chauhan",
    description: "Technical Head, IEEE DITU",
    github: "",
    linkedin: "",
  },
  {
    porfileUrl: "/avatars/shreyal.svg",
    name: "Shreyal Jain",
    description: "Joint Secretary, IEEE DITU",
    github: "https://github.com/shreyal0007",
    linkedin: "https://www.linkedin.com/in/shreyal-jain-78b75521b/",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "Pratik Singh",
    description: "Joint Secretary, IEEE DITU",
    github: "https://github.com/Pratik-11",
    linkedin: "https://www.linkedin.com/in/pratik-singh-6a22221ba/",
  },
  {
    porfileUrl: "/avatars/tanishq.svg",
    name: "Tanishq Jain",
    description: "Webmaster, IEEE DITU",
    github: "https://github.com/tanishqJain16/",
    linkedin: "https://www.linkedin.com/in/tanishq-jain-9a8bb022b/",
  },
  {
    porfileUrl: "/avatars/vaibhav.svg",
    name: "Vaibhav Aswal",
    description: "Webmaster, IEEE DITU",
    github: "https://github.com/VaibhavAswal",
    linkedin: "https://www.linkedin.com/in/vaibhavaswal/",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "Srajan Sharma",
    description: "Design Head, IEEE DITU",
    github: "",
    linkedin: "https://www.linkedin.com/in/srajan-sharma-01591124a/",
  },
  {
    porfileUrl: "/avatars/abbas.svg",
    name: "Mohd. Abbas",
    description: "Social Media Head, IEEE DITU",
    github: "",
    linkedin: "https://www.linkedin.com/in/mohd-abbas-209a75222/",
  },
];
