export const counsellors = [
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
];

export const studentCouncil = [
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "",
    linkedin: "",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",

    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
  {
    porfileUrl: "/avatars/ps-sharma.jpeg",
    name: "P.S Sharma",
    description: "hfghcgadvjavcghavchv gfuajvj jhcabcb jhjhbcwef",
    github: "https://github.com/ieee-ditu",
    linkedin: "https://linkedin.com/ieee-ditu",
  },
];
