export const sliderCards = [
    {
        id: 1,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title1" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 2,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title2" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 3,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title3" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 4,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title4" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 5,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title5" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 6,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title6" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 7,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title7" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
];

