export const sliderCards = [
    {
        id: 1,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title1" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 2,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title2" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 3,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title3" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 4,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title4" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 5,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title5" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 6,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title6" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
    {
        id: 7,
        horiCardImage: "https://picsum.photos/200/300" ,
        horiCardTitle: "title7" ,
        horiCardCoordinator: "blahblah " ,
        horiCardSpeaker: "blahblah" ,
        horiCardDate: "dd/mm/yyy",
    },
];

export const verCards = [
    {   
        id:1,
        verCardImage: "https://picsum.photos/200/300",
        verCardTitle: "title1",
        verCardCoordinator: "blahblah",
        verCardSpeaker: "blahblah",
        verCardDate: "dd/mm/yyyy",
        verCardContent: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit tenetur perferendis obcaecati. Mollitia atque nulla pariatur iste nostrum nisi minus illo est! Nihil non quas alias commodi voluptas nemo dolorum.",
    },
    {   
        id:2,
        verCardImage: "https://picsum.photos/200/300",
        verCardTitle: "title2",
        verCardCoordinator: "blahblah",
        verCardSpeaker: "blahblah",
        verCardDate: "dd/mm/yyyy",
        verCardContent: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit tenetur perferendis obcaecati. Mollitia atque nulla pariatur iste nostrum nisi minus illo est! Nihil non quas alias commodi voluptas nemo dolorum.",
    },
    {   
        id:3,
        verCardImage: "https://picsum.photos/200/300",
        verCardTitle: "title3",
        verCardCoordinator: "blahblah",
        verCardSpeaker: "blahblah",
        verCardDate: "dd/mm/yyyy",
        verCardContent: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit tenetur perferendis obcaecati. Mollitia atque nulla pariatur iste nostrum nisi minus illo est! Nihil non quas alias commodi voluptas nemo dolorum.",
    },
];